#!/bin/sh

export CC=pnacl-clang
export CXX=pnacl-clang++
export AR=pnacl-ar
export RANLIB=pnacl-ranlib
export READELF=pnacl-readelf
export CFLAGS='-I/home/david/pnacl/nacl_sdk/pepper_37/include -I/home/david/pnacl/nacl_sdk/pepper_37/include/pnacl -I/home/david/pnacl/nacl_sdk/pepper_37/ports/include'
export CPPFLAGS=
export CXXFLAGS=
export LDFLAGS='-L/home/david/pnacl/nacl_sdk/pepper_37/lib/pnacl/Release -L/home/david/pnacl/nacl_sdk/pepper_37/ports/lib/newlib_pnacl/Release'
export AR_FLAGS=cr
export PKG_CONFIG_LIBDIR=/home/david/pnacl/nacl_sdk/pepper_37/toolchain/linux_pnacl/usr/lib/pkgconfig
#export PKG_CONFIG_PATH=/d/nacl_sdk/pepper_33/toolchain/linux_pnacl/usr/lib/pkgconfig

./configure \
    --target-os=linux \
    --arch=pnacl \
    --disable-runtime-cpudetect \
    --cross-prefix=pnacl- \
    --cc=pnacl-clang \
    --ld=pnacl-clang++ \
    --pkg_config=pkg-config \
    --enable-static \
    --enable-cross-compile \
    --disable-ffplay \
    --disable-ffprobe \
    --disable-ffserver \
    --disable-asm \
    --disable-inline-asm \
    --disable-indevs \
    --disable-protocols \
    --disable-network \
    --enable-protocol=file \
    --disable-demuxer=rtsp \
    --disable-demuxer=image2 \
    --disable-doc \
    --disable-htmlpages \
    --disable-bsfs \
    --disable-debug \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-network \
    --disable-encoders \
    --disable-filters \
    --disable-decoders \
    --extra-libs='-lppapi_simple -lppapi -lppapi_cpp -lnacl_io' \
    --enable-libvorbis \
    --enable-libtheora \
    --enable-encoder=libtheora \
    --enable-encoder=libvorbis \
    --enable-decoder=pcm_s16le \
    --enable-decoder=vp8 \
    --enable-filter=aresample \
    --disable-muxers \
    --enable-muxer=ogg \
    --disable-demuxers \
    --enable-demuxer=matroska \
    --enable-demuxer=pcm_s16le \
    --enable-demuxer=wav 
    
