#!/bin/sh


PNACL_TC_PATH= $(abspath ${NACL_SDK_ROOT}/toolchain/linux_pnacl)
PNACL_FINALIZE=${PNACL_TC_PATH}/bin/pnacl-finalize
export CC=pnacl-clang
export CXX=pnacl-clang++
export AR=pnacl-ar
export RANLIB=pnacl-ranlib
export READELF=pnacl-readelf
export CFLAGS='-I${NACL_SDK_ROOT}/include -I${NACL_SDK_ROOT}/include/pnacl -I${NACL_SDK_ROOT}/ports/include'
export CPPFLAGS=
export CXXFLAGS=
export LDFLAGS='-L${NACL_SDK_ROOT}/lib/pnacl/Release -L${NACL_SDK_ROOT}/ports/lib/newlib_pnacl/Release'
export AR_FLAGS=cr
export PKG_CONFIG_LIBDIR=${PNACL_TC_PATH}/usr/lib/pkgconfig

#export PKG_CONFIG_PATH=/d/nacl_sdk/pepper_33/toolchain/linux_pnacl/usr/lib/pkgconfig

./configure \
    --target-os=linux \
    --arch=pnacl \
    --disable-runtime-cpudetect \
    --cross-prefix=pnacl- \
    --cc=pnacl-clang \
    --ld=pnacl-clang++ \
    --pkg_config=pkg-config \
    --enable-static \
    --enable-cross-compile \
    --disable-ffplay \
    --disable-ffprobe \
    --disable-ffserver \
    --disable-asm \
    --disable-inline-asm \
    --disable-indevs \
    --disable-protocols \
    --disable-network \
    --enable-protocol=file \
    --disable-demuxer=rtsp \
    --disable-demuxer=image2 \
    --disable-doc \
    --disable-htmlpages \
    --disable-bsfs \
    --disable-debug \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-network \
    --disable-encoders \
    --disable-filters \
    --disable-decoders \
    --extra-libs='-lppapi_simple -lppapi -lppapi_cpp -lnacl_io' \
    --enable-libvorbis \
    --enable-libtheora \
    --enable-encoder=libtheora \
    --enable-encoder=libvorbis \
    --enable-decoder=pcm_s16le \
    --enable-decoder=vp8 \
    --enable-filter=aresample \
    --disable-muxers \
    --enable-muxer=ogg \
    --disable-demuxers \
    --enable-demuxer=matroska \
    --enable-demuxer=pcm_s16le \
    --enable-demuxer=wav

make
${PNACL_FINALIZE} -o ./pnacl/ffmpeg.pexe ./ffmpeg
nacl
